// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uolzmxjpuzgmisswuygp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvbHpteGpwdXpnbWlzc3d1eWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDEwOTQsImV4cCI6MjA2MDkxNzA5NH0.a8Cd5yD7S3iIlhDahiHTtSsIfMq9vor9ebVBzoS2aKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);